// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	domain "api/core/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PurchaseRepository is an autogenerated mock type for the PurchaseRepository type
type PurchaseRepository struct {
	mock.Mock
}

// GetPurchase provides a mock function with given fields: ctx, id
func (_m *PurchaseRepository) GetPurchase(ctx context.Context, id string) (domain.Purchase, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPurchase")
	}

	var r0 domain.Purchase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Purchase, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Purchase); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Purchase)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, purchase
func (_m *PurchaseRepository) Save(ctx context.Context, purchase domain.Purchase) (string, error) {
	ret := _m.Called(ctx, purchase)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Purchase) (string, error)); ok {
		return rf(ctx, purchase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Purchase) string); ok {
		r0 = rf(ctx, purchase)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Purchase) error); ok {
		r1 = rf(ctx, purchase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, id
func (_m *PurchaseRepository) Search(ctx context.Context, id string) (domain.Purchase, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.Purchase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Purchase, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Purchase); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Purchase)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPurchaseRepository creates a new instance of PurchaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPurchaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PurchaseRepository {
	mock := &PurchaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
