// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"api/adapters/incoming/http"
	"api/adapters/outgoing/db"
	"api/adapters/outgoing/db/mongoimpl"
	"api/adapters/outgoing/smtp"
	"api/core/usecases"
	"api/infra/config"
)

// Injectors from wire.go:

func InitializeUsersHandler() *http.UserHandler {
	configConfig := config.NewConfigProvider()
	localCache := db.NewCacheProvider(configConfig)
	database := mongoimpl.NewMongoClientProvider(configConfig)
	userRepository := db.NewUserRepositoryProvider(configConfig, localCache, database)
	notifier := smtp.NewNotifierProvider()
	userService := usecases.NewUserUseCaseProvider(userRepository, notifier)
	userHandler := http.NewUserHandlerProvider(userService)
	return userHandler
}
